# NumPy-упражнения

Теперь, когда мы узнали о NumPy, давайте проверим ваши знания. Мы начнем с нескольких простых задач, а затем вам будут заданы более сложные вопросы.

#### Import NumPy as np

In [ ]:
import numpy as np

#### Создайте массив из 10 нулей

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Создайте массив из 10 единиц

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Создайте массив из 10 семёрок

In [ ]:
arr = np.full(10, 7.)
print(arr)

[7. 7. 7. 7. 7. 7. 7. 7. 7. 7.]


array([7., 7., 7., 7., 7., 7., 7., 7., 7., 7.])

#### Создайте массив целых чисел от 10 до 60 (включая 60)

In [ ]:
arr = np.arange(10, 61)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60]


#### Создайте массив всех четных целых чисел от 10 до 50

In [ ]:
arr = np.arange(10, 51)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


#### Создайте матрицу 3x3 со значениями в диапазоне от 1 до 9.

In [ ]:

arr = np.arange(1, 10).reshape(3, 3)
print(arr)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### Создайте единичную матрицу 4x4

In [ ]:
arr = np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


#### Используйте NumPy для генерации случайного числа от 0 до 1¶ (результат может отличаться)

In [ ]:
random_number = np.random.rand()
print(random_number)

0.1671985932513207


#### Используйте NumPy для создания массива из 25 случайных чисел, выбранных из стандартного нормального распределения.

In [ ]:
random_array = np.random.randn(25)
print(random_array)

[ 0.6141461   1.26655455  0.03641163 -0.04550924  1.17158066  0.34371015
 -0.94688745  0.06339997 -0.13700815  0.95675636  1.23730263 -0.39334187
  0.29319905  0.55795422 -0.52501064  1.38412182 -0.19560937  0.28016806
  0.263692    1.63532954  0.23058206  0.4118036  -0.88502324  0.16793139
  0.83302564]


#### Создайте следующую матрицу:

In [ ]:
arr = np.arange(0.01, 1.01, 0.01).reshape(10, 10)
print(arr)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


#### Создайте следующую матрицу:

In [ ]:
arr = np.arange(0.01, 2.01, 0.02).reshape(10, 10)
print(arr)

[[0.01 0.03 0.05 0.07 0.09 0.11 0.13 0.15 0.17 0.19]
 [0.21 0.23 0.25 0.27 0.29 0.31 0.33 0.35 0.37 0.39]
 [0.41 0.43 0.45 0.47 0.49 0.51 0.53 0.55 0.57 0.59]
 [0.61 0.63 0.65 0.67 0.69 0.71 0.73 0.75 0.77 0.79]
 [0.81 0.83 0.85 0.87 0.89 0.91 0.93 0.95 0.97 0.99]
 [1.01 1.03 1.05 1.07 1.09 1.11 1.13 1.15 1.17 1.19]
 [1.21 1.23 1.25 1.27 1.29 1.31 1.33 1.35 1.37 1.39]
 [1.41 1.43 1.45 1.47 1.49 1.51 1.53 1.55 1.57 1.59]
 [1.61 1.63 1.65 1.67 1.69 1.71 1.73 1.75 1.77 1.79]
 [1.81 1.83 1.85 1.87 1.89 1.91 1.93 1.95 1.97 1.99]]


#### Создайте массив из 20 линейно расположенных точек между 1 и 2:

In [ ]:
arr = np.linspace(1, 2, 20)
print(arr)

[1.         1.05263158 1.10526316 1.15789474 1.21052632 1.26315789
 1.31578947 1.36842105 1.42105263 1.47368421 1.52631579 1.57894737
 1.63157895 1.68421053 1.73684211 1.78947368 1.84210526 1.89473684
 1.94736842 2.        ]


array([1.        , 1.05263158, 1.10526316, 1.15789474, 1.21052632,
       1.26315789, 1.31578947, 1.36842105, 1.42105263, 1.47368421,
       1.52631579, 1.57894737, 1.63157895, 1.68421053, 1.73684211,
       1.78947368, 1.84210526, 1.89473684, 1.94736842, 2.        ])

## Индексация и выбор Numpy

Теперь вам будет предоставлено несколько матриц, и вам нужно воспроизвести полученные выходные данные матрицы:

In [ ]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# НАПИШИТЕ ЗДЕСЬ КОД, КОТОРЫЙ ВОСПРОИЗВОДИТ ВЫВОД ЯЧЕЙКИ НИЖЕ
# БУДЬТЕ ОСТОРОЖНЫ, ЧТОБЫ НЕ ЗАПУСТИТЬ ЯЧЕЙКУ НИЖЕ, ИНАЧЕ ВЫ НЕ УДАЛИТЕ ОТВЕТ

In [ ]:
sub_mat = mat[1:4, 1:4]
print(sub_mat)

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [ ]:
# НАПИШИТЕ ЗДЕСЬ КОД, КОТОРЫЙ ВОСПРОИЗВОДИТ ВЫВОД ЯЧЕЙКИ НИЖЕ
# БУДЬТЕ ОСТОРОЖНЫ, ЧТОБЫ НЕ ЗАПУСТИТЬ ЯЧЕЙКУ НИЖЕ, ИНАЧЕ ВЫ НЕ УДАЛИТЕ ОТВЕТ

In [ ]:
sub_mat[-1][-1]

19

19

In [ ]:
# НАПИШИТЕ ЗДЕСЬ КОД, КОТОРЫЙ ВОСПРОИЗВОДИТ ВЫВОД ЯЧЕЙКИ НИЖЕ
# БУДЬТЕ ОСТОРОЖНЫ, ЧТОБЫ НЕ ЗАПУСТИТЬ ЯЧЕЙКУ НИЖЕ, ИНАЧЕ ВЫ НЕ УДАЛИТЕ ОТВЕТ

In [ ]:
sub_mat = mat[0:3, 2:3]
print(sub_mat)

[[ 3]
 [ 8]
 [13]]


array([[ 3],
       [ 8],
       [13]])

In [ ]:
# НАПИШИТЕ ЗДЕСЬ КОД, КОТОРЫЙ ВОСПРОИЗВОДИТ ВЫВОД ЯЧЕЙКИ НИЖЕ
# БУДЬТЕ ОСТОРОЖНЫ, ЧТОБЫ НЕ ЗАПУСТИТЬ ЯЧЕЙКУ НИЖЕ, ИНАЧЕ ВЫ НЕ УДАЛИТЕ ОТВЕТ

In [ ]:
sub_mat = mat[4, :]
print(sub_mat)

[21 22 23 24 25]


array([21, 22, 23, 24, 25])

In [ ]:
# НАПИШИТЕ ЗДЕСЬ КОД, КОТОРЫЙ ВОСПРОИЗВОДИТ ВЫВОД ЯЧЕЙКИ НИЖЕ
# БУДЬТЕ ОСТОРОЖНЫ, ЧТОБЫ НЕ ЗАПУСТИТЬ ЯЧЕЙКУ НИЖЕ, ИНАЧЕ ВЫ НЕ УДАЛИТЕ ОТВЕТ

In [ ]:
sub_mat = mat[2:4, :]
print(sub_mat)

[[11 12 13 14 15]
 [16 17 18 19 20]]


array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

### Теперь сделайте следующее

#### Получите сумму всех значений в заданной матрице mat

In [ ]:
sum_of_values = np.sum(mat)
print(sum_of_values)

325


#### Получите средне квдратическое отклонение (standard deviation) значений в заданной матрице mat (подсказка: функция .std)

In [ ]:
sd= mat.std()
print(sd)

7.211102550927978


#### Получить сумму всех столбцов в заданной матрице mat

array([55, 60, 65, 70, 75])

In [ ]:
column_sums = np.sum(mat, axis=0)
print(column_sums)

[55 60 65 70 75]
